spring:
  application:
    name: criar-cenario-testes

  data:
    mongodb:
      uri: ${MONGO_URI_NUVEM}
      database: geradorcenarios

server:
  address: 0.0.0.0
  port: 8089
  error:
    include-message: always
    include-exception: true

agents:
  directory: ${AGENTS_DIRECTORY:}

ai:
  active-provider: openai
  fallback-provider: gemini

  openai:
    api-key: ${OPENAI_API_KEY}
    model: gpt-4.1
    url: https://api.openai.com/v1/chat/completions
    max-tokens: 4000

  gemini:
    api-key: ${GEMINI_API_KEY}
    model: gemini-2.5-flash
    url: https://generativelanguage.googleapis.com/v1beta/models
    max-tokens: 4000

jira:
  base-url: ${JIRA_BASE_URL:}
  email: ${JIRA_EMAIL:}
  api-token: ${JIRA_API_TOKEN:}
  issue-endpoint: /rest/api/3/issue

logging:
  level:
    root: INFO
    br.com: DEBUG
