package com.br.criarcenariotestes.business.autoqa.model.failure;

public enum FailureCategory {
    ASSERTION_FAILURE,
    LOCATOR_FAILURE,
    TIMEOUT_FAILURE,
    ELEMENT_NOT_FOUND,
    HTTP_STATUS_FAILURE,
    RESPONSE_BODY_FAILURE,
    CONTRACT_FAILURE,
    DATA_FAILURE,
    AUTHENTICATION_FAILURE,
    AUTHORIZATION_FAILURE,
    ENVIRONMENT_FAILURE,
    DEPENDENCY_FAILURE,
    CONFIGURATION_FAILURE,
    COMPILATION_FAILURE,
    SYNTAX_FAILURE,
    IMPORT_FAILURE,
    SETUP_FAILURE,
    TEARDOWN_FAILURE,
    NETWORK_FAILURE,
    APPLICATION_DEFECT,
    TEST_DEFECT,
    FLAKY_TEST,
    UNKNOWN
}